# Note: After loading intel's latest compiler module
#		intel/15.0.2
#	need to also load the c++11 routines module:
#		cxx11/4.9.1
#	Some flags to set:
#			MKL_MIC_ENABLE=1 OFFLOAD_REPORT=2

MICCXX = icpc
MICFLAGS = -O3 -std=c++11 -openmp

CPU_PROGS = 
GPU_PROGS = 
MPI_PROGS = 
MIC_PROGS = star-discrepancy_mic
PROGS = ${CPU_PROGS} ${GPU_PROGS} ${MPI_PROGS} ${MIC_PROGS}
all : ${PROGS}

star-discrepancy_mic : star-discrepancy_mic.cpp
	${MICCXX} ${MICFLAGS} -o $@ $^

clean :
	rm ${PROGS}
